### ISSUE TITLE
Compilation fail (2 R versions, Windows & Linux)

### ISSUE THREAD

**Issue by edammer** [steven-shuken/permFDP#1]
Compilation of C source fails for me on both R v4.0.2 on Windows and R v4.2.0 on linux (attached logs of the compilation errors on each platform are given).

[Rv4.2.0_permFDP_compFail.txt](https://github.com/steven-shuken/permFDP/files/10496664/Rv4.2.0_permFDP_compFail.txt)
[Rv4.0.2_permFDP_compFail.txt](https://github.com/steven-shuken/permFDP/files/10496665/Rv4.0.2_permFDP_compFail.txt)

I appreciate any assistance.

Eric

**Comment by steven-shuken** [comment]
Hi Eric,
Thanks for bringing this to my attention. It is a problem with Boost Headers (BH) so I will have to reach out to the author of that package to fix this.
-Steven
