### ISSUE TITLE
Calculated thresholds are always 1/2 of the lowest p-value

### ISSUE THREAD

**Issue by stefftaelman** [steven-shuken/permFDP#4]
I've noticed that when there is no significance in a dataset (as compared with other multiple testing correction methods), the p-value threshold generated by `permFDP` is always exactly half of the smallest p-value in the vector supplied to it. This seems to be invariant of the statistical test or transformation method, so it must be due to permFDP itself. 

**Is this just a mathematical quirk or is there a bug here?**

Some examples:
![thresh: 0.04; p-val: 0.08](https://user-images.githubusercontent.com/39267023/231423193-a239bdd7-7fc7-444d-ac79-73f1034fe694.png)
![thresh: 0.08; p-val: 0.16](https://user-images.githubusercontent.com/39267023/231423218-d86d6ec3-5213-444a-bc94-e64e3ce96806.png)
![thresh: 0.1675; p-val: 0.3350](https://user-images.githubusercontent.com/39267023/231423223-05723db9-a242-41ff-8309-cd737e2e0a20.png)
![thresh: 0.05; p-val: 0.10](https://user-images.githubusercontent.com/39267023/231423227-c25b4591-1807-42b6-99ca-e8e38a19720b.png)
![thresh: 0.0029; p-val: 0.0058](https://user-images.githubusercontent.com/39267023/231423231-e17e930d-00c3-4e9c-b34a-d004faf0140f.png)

**Comment by steven-shuken** [comment]
<img width="811" alt="230412 arbitrary threshold screenshot" src="https://user-images.githubusercontent.com/98045487/231487068-47d51988-ab23-47ba-a2fe-44d5c31d49cc.png">

**Comment by stefftaelman** [comment]
Alright, makes a lot of sense. Thanks for the quick reply!
